name:                b2c
version:             0.5.0.0
github:              "eunikolsky/b2c"
license:             BSD3
author:              "Eugene Nikolsky"
maintainer:          "e@egeek.me"
copyright:           "2021 Eugene Nikolsky"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eunikolsky/b2c#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src
  dependencies:
    - bytestring
    - containers
    - data-default
    - iCalendar
    - megaparsec
    - mtl
    - time
    - transformers
    - uuid

executables:
  b2c:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - b2c
    - bytestring

tests:
  b2c-test:
    main:                Spec.hs
    source-dirs:         test
    extra-source-files:  test/contacts.vcf
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - b2c
    - filepath
    - data-default
    - directory
    - hspec
    - iCalendar
    - mtl
